version: '3.9'

services:
  voisinup:
    image: voisinup
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - VoisinUpDbConnection=Host=db;Port=5432;Database=voisinup;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voisinup
    # le montage du script SQL d'init
    volumes:
      - ./DB_creation.sql:/docker-entrypoint-initdb.d/DB_creation.sql:ro
    # ⚠️  pas de volume persistant : on veut tout perdre à chaque rebuild
    # pas de `db_data:` ici !