version: '3.9'

services:
  voisinup:
    image: voisinup
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # expose l'API sur le port 8080 du serveur
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - VoisinUpDbConnection=Host=db;Port=5432;Database=voisinup;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voisinup
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./DB_creation.sql:/docker-entrypoint-initdb.d/DB_creation.sql:ro

volumes:
  db_data: